### ISSUE TITLE
Fascicularia pitcairniifolia ? a synonym of F. bicolor

### ISSUE THREAD

**Issue by japonicus** [BSBI/mapmate-taxon-requests#16]
Mapmate recognises Fascicularia pitcairniifolia (Verl.) Mez as an accepted taxon (v38791zj)

There are records in the DDb for this taxon from the Isles of Scilly.

In Stace ed. 3 Fascicularia pitcairniifolia is treated as **sensu Lousley, auct. non (Verl.) Mez** and synonymized to F. bicolor.

Is the independent presence in the MapMate dictionary of Fascicularia pitcairniifolia (Verl.) Mez a mistake?

**Comment by sacrevert** [comment]
I think this is just due to out-of-date information. Clement & Foster (1994) list F. pitcairniifolia (Verlot) Mez but Stace et al. (2003) list F. bicolor and Ochagavia carnea in this family, as do Parslow & Bennalick (2017) and the New Atlas CDROM. 

Presumably the fact that VC1 recorders, including Parslow, have recorded F. pitcairniifolia s.s. in recent years (according to the DDb) is because it is available in Mapmate and they are treating it as a synonym of F. bicolor (otherwise I cannot see why F. pitcairniifolia s.s. is absent from the New Flora of the Isles of Scilly (Parslow & Bennalick 2017)).

As far as I can see all the records of F. pitcairniifolia s.s. should be updated to the sensu Lousley, auct. non (Verl.) Mez concept.
