### ISSUE TITLE
Zannichellia obtusifolia Talabera, Garcia-Mur & H.Smit

### ISSUE THREAD

**Issue by tangiblegains** [BSBI/mapmate-taxon-requests#9]
Ken Adams has requested the inclusion of Zannichellia obtusifolia Talabera, Garcia-Mur & H.Smit in MM. The record has been confirmed by CDP. There do not appear to be any issues with taxonomy. First for GB in the wild. This taxon would also need adding to the DDb.

**Comment by japonicus** [comment]
I've added this to the DDb.

(there's a  typo in the authority name, Talabera should be Talavera according to theplantlist and IPNI)

@tangiblegains please could you ask Ken to send me a copy of the record for direct addition to the DDb (so that this doesn't get lost, if it takes a while to add to MapMate)

**Comment by tangiblegains** [comment]
I have asked Ken to send records details for inclusion in the DDb.

**Comment by japonicus** [comment]
Stace 4 names will all be included
